- readme.markdown
* Document that callback may be called with 3rd arg, pkg.
* Better document what opts.package consists of.
* Change some param names to more clearly distinguish what they refer
to.
> Update docs re: input and cb args.

- lib/async.js
- test/pathfilter.js
- test/precedence.js
- test/resolver.js
This fixes async resolution when looking for a package.json file.
Previously a regex was being used that was not allowing the recursive
behavior the code is attempting. Replacing with path.dirname fixes the
issue.
Fixes #76
> Use path.dirname to walk up looking for a package.json

- lib/node-modules-paths.js
This change moves 'prefix' test to happen after the absolute path is
resolved. Without it, the prefix tests never actually fire when starting
with a relative path, and the resulting dirs all end up looking like
`[ '/C:..', '/C:...' ]` instead of `[ 'C:...', 'C:...' ]`
> Fix node_modules paths on Windows

- lib/async.js
This creates much more relevant stack traces for user input errors
> Create error outside process.nextTick

- lib/async.js
- lib/sync.js
- test/mock.js
- test/resolver.js
When using node's `require.resolve` there's a [`err.code` property set on error objects](https://github.com/nodejs/node/blob/e11fe0c2777561827cdb7207d46b0917ef3c42a7/lib/module.js#L333).
This change adds the same to `err.code` property to errors objects to match node's behavior.
> err.code = 'MODULE_NOT_FOUND'

- appveyor.yml
- lib/node-modules-paths.js
- package.json
- test/faulty_basedir.js
- test/node-modules-paths.js
- Add `path-parse` since `node` <= 0.10 doesn’t have `path.parse`
This PR adds tests for `node-modules-paths`, and also makes them pass in Windows. In order to retain compatibility with node 0.10 and earlier, which lacks `path.parse`, I'm adding the `path-parse` dependency.
If we ever wish to drop 0.6, 0.8, and 0.10 compat, then we can drop the runtime dependency as well.
This should fix #106, may make #107 unnecessary, closes #52, and affects #88.
The `node-modules-paths` tests are a bit loose out of necessity - I didn't want to simply duplicate the implementation to test them, and since `$PWD` will differ across machines, I didn't want to couple the tests to a individual machine's paths.
> [Tests] [Refactor] refactor `node-modules-paths` and add tests.

- lib/async.js
- lib/sync.js
- test/resolver.js
- test/resolver/same_names/foo.js
- test/resolver/same_names/foo/index.js
- test/resolver_sync.js
The current behavior is not in line with node's implementation.
```js
require.resolve('./foo') // 'foo.js'
require.resolve('./foo/') // 'foo/index.js'
resolve.sync('./foo') // 'foo.js'
resolve.sync('./foo/') // 'foo.js'
```
It affects both, sync and async methods and I fixed both of them.
Related Jest issue with more details https://github.com/facebook/jest/issues/3199
Fixes #51. Closes #53.
> [Fix] correctly resolve dir paths when file with the same name exists

- lib/node-modules-paths.js
- readme.markdown
- test/resolver/symlinked/.gitignore
- test/resolver/symlinked/_/.gitignore
- test/symlinks.js
> add preserveSymlinks option

- lib/async.js
- test/resolver.js
It looks like the non-relative lookup [here](https://github.com/browserify/resolve/blob/v1.5.0/lib/async.js#L43) was missed when adding the `opts.package` feature (which I would like to utilize).
> support opts.package in non-relative lookups

- lib/sync.js
- readme.markdown
- test/pathfilter.js
Fixes #142.
It works fine on CodeSandbox since the end of November. Although not being familiar with the project, I might have missed something.
> Make loadAsFileSync() work the same as async loadAsFile()

- lib/node-modules-paths.js
- readme.markdown
- test/symlinks.js
> breaking change: preserveSymlinks is false by default

- test/pathfilter_sync.js
@substack I want to use `node-browser-resolve` in a synchronous way, it requires the `pathfilter` option though, so I've added it to the synchronous resolve function.
> Add support for pathfilter in resolve.sync

- lib/async.js
- lib/sync.js
- test/resolver.js
- test/resolver_sync.js
Incorporates changes submitted by @jmm to fix Issue #60, resolves test errors. Was originally PR #64.
Fixes #60. Closes #64. Replaces #161.
> [New] include filename in error message

- lib/async.js
- lib/sync.js
- test/resolver.js
- test/resolver_sync.js
PR #162 introduced a `parent` variable that contains either the full
filename of the requiring module or the `basedir`. Some of the places
where `basedir` was used were updated to use `parent` instead, but
that's not correct; the `path.resolve()` calls would receive the full
filename instead of the directory name.
This patch reverts the improper `parent` uses to `basedir`.
> [Fix] resolution when `filename` option is passed

- lib/async.js
- lib/normalize-options.js
- lib/sync.js
Split out of #170.
This PR adds a noop function used to normalize the options passed to `resolve`. The goal is for third-party environments like PnP to be able to override this file (and only this file) to set new default options more adapted to the current process resolution.
> Implements a "normalize-options" pseudo-hook

- lib/async.js
- test/faulty_basedir.js
Patches an issue that would cause a type error to be thrown when `fs.realpath` would return an `ENOENT` and `preserveSymlinks` was set to `false`.
Closes #181.
> [Fix] TypeError: Path must be a string. Received undefined

- lib/async.js
- test/mock.js
This offers a small but useful performance improvement by avoiding unnecessary stat calls.
Fixes #116
> [Refactor] check existence of `node_modules`

- lib/sync.js
- test/mock_sync.js
This brings the same perf improvements as in 4cf89280c7446b396b67c43900b297b6b3e0907a (https://github.com/browserify/resolve/pull/190) but for the sync version
Refs #116
> [refactor] (sync) check existence of node_modules

- lib/async.js
- lib/sync.js
- readme.markdown
- test/mock.js
- test/mock_sync.js
This is a backport of 4cf89280c7446b396b67c43900b297b6b3e0907a and fa11d4804cdd89250404c5efff5256755887331c (https://github.com/browserify/resolve/pull/190 and https://github.com/browserify/resolve/pull/191) to the 1.x branch.
This adds the `isDirectory` option which is needed to drive the directory lookups.
This offers a small but useful performance improvement by avoiding unnecessary stat calls.
Because of the added option this is a MINOR change.
Refs #116
> [New] Add `isDirectory`; use to speed up `node_modules` lookups

- lib/node-modules-paths.js
- test/node-modules-paths.js
This is to fix issue #155 where paths don't resolve when it refers to a networked location. The leading backslash gets stripped off which turns paths such as '\\\\ip\\dir' into '\\ip\dir'.
> correctly resolve paths that are on networked drives

- readme.markdown
This PR changes the URL for the CI status badge to the right one.
> [Docs] fix CI status badge

- index.js
- lib/async.js
- lib/is-core.js
- lib/sync.js
- test/core.js
- test/symlinks.js
Context:
I'm trying to use Yarn 2 (with PnP) in Babel.
Babel depends on `browserify`, which depends on `browser-resolve` which depends on an older version of `resolve` without PnP support (1.1.7).
I tried to upgrade `resolve` in `browser-resolve`, but a test started failing because it checked for `toString` resolution.
Since this worked in `resolve` 1.1.7, was the behavior changed on purpose?
> Do not leak Object.prototype when checking for core modules

- lib/async.js
- lib/sync.js
There's a slight difference between the sync and async codepaths in that the `isCore` async check is done in the `loadNodeModules` callback rather than right before the call.
I'm not sure how to test it though since it has the same behaviour except that packageIterator (from #205) won't be called with core packages.
> Fixes isCore async check

- lib/async.js
- lib/sync.js
- readme.markdown
- test/resolver.js
- test/resolver/baz/package.json
- test/resolver_sync.js
Offers a fix for the problem described in https://github.com/browserify/resolve/issues/199#issuecomment-570225108
This PR offers a way to alter the default package path generation. The default implementation still uses `path.join('/.../node_modules', packageName)` (which cannot work for PnP when using the link protocol for the reasons described [here](https://github.com/browserify/resolve/issues/199#issuecomment-570393826)), but the PnP resolver (automatically configured thanks to #174) will directly return the path to the package regardless of the dependency type, shortcutting the default logic.
One big advantage of this diff is that it's semver-minor, which avoids having to upgrade all third-party consumers (which I really don't have the bandwidth to do 😅).
> Implements packageIterator

- appveyor.yml
- lib/async.js
- lib/sync.js
- test/resolver.js
- test/resolver_sync.js
> fix: correct behavior when requiring `.` with same name

- appveyor.yml
- lib/async.js
- lib/sync.js
As discussed in https://github.com/facebook/jest/issues/9776
Docs: https://nodejs.org/api/fs.html#fs_fs_realpath_native_path_options_callback
didn't bother with `process.bindings` as we really shouldn't use those
> feat: use native `realpath` if available to unwrap symlinks

- lib/async.js
- lib/sync.js
https://github.com/browserify/resolve/commit/535ec22acf6d5cc4fa3665ab6dbb6755519e6deb#diff-688ede0ee2da1fa3d89f2fc485f39273R8
This change caused some issues for the users of Cypress Cucumber Preprocessor - https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/362
`putting     "resolve": "1.15.1"`
in package.json resolutions helps.
I'm guessing we never, directly or indirectly, call the `maybeUnwrapSymlink` function so having realpath not being defined was never a problem for us. 
I'd appreciate a tweak here. I'm also guessing we might not the only ones that will bump into this problem in the future.
> Moving the realpath resolution to a function that uses it, so it doesn't fail on lib/sync import

- lib/async.js
- lib/sync.js
- readme.markdown
- test/mock.js
- test/mock_sync.js
Not sure how to write tests for this one. Ideas?
I also went with passing the implementation to `maybeUnwrap` so consumer wouldn't have to care about the option, not sure if it's a good idea or not.
(This is probably the one we want in Jest so we can plug in the hacky `process.bindings` one on node 8...)
> [New] `sync`/`async`: add `realpath`/`realpathSync` options

- lib/async.js
- lib/sync.js
- readme.markdown
- test/shadowed_core.js
Setting `includeCoreModules: false` makes it possible to resolve as if the core modules did not exist.
This can be useful in a bundler like rollup where the user may be targeting web, where node builtins are not relevant.
Refs https://github.com/rollup/plugins/pull/637
> add 'includeCoreModules' option

- lib/async.js
- lib/sync.js
- readme.markdown
- test/mock.js
- test/mock_sync.js
From discussion in https://github.com/facebook/jest/issues/11034
While `readFile` and `readFileSync` allows consumers to cache the FS operation, `resolve` will always do `JSON.parse` on the file content. `readPkg` and `readPkgSync` allows users to also cache that, if they want, avoiding the extra and potentially redundant JSON parsing.
This change largely makes `readFile` and `readFileSync` redundant IMO (as the only time `resolve` actually reads files is to read and parse `package.json` files), so for v2 it's a possibility to remove them.
> [New] add `readPackage` and `readPackageSync`

- lib/sync.js
> Do not throw on missing files in isFile/Dir

- .eslintrc
- bin/resolve
- package.json
Very simple addition. Allows `resolve` to be installed globally or to be used as part of an npm script.
**Example**
I want to add `eslint` and a [TAP reporter](https://github.com/sindresorhus/eslint-tap) to my project. My `package.json`:
_**Before**_
``` json
{
"devDependencies": {
"eslint": "*",
"eslint-tap": "*"
},
"scripts": {
"test": "eslint . --format node_modules/eslint-tap/tap.js"
}
}
```
Bad. No guarantee that formatter will exist at that path.
_**After**_
``` json
{
"devDependencies": {
"resolve": "*",
"eslint": "*",
"eslint-tap": "*"
},
"scripts": {
"test": "eslint . --format $(resolve eslint-tap/tap)"
}
}
```
Good. Path is not hard coded.
> Add simple CLI utility

- .eslintrc
- lib/async.js
- lib/homedir.js
- lib/sync.js
- package.json
- test/home_paths.js
- test/home_paths_sync.js
Note, this is a rarely used feature that should be aggressively avoided, but it‘s important to minimize gaps between node and this package.
Fixes #163.
I'm uncertain if I'll backport this to the 1.x branch, primarily because of the risk of unintentional breakage. However, since virtually nobody is going to be using these directories, and since it's only going to potentially _start_ resolving bare specifiers where previously there was an error, this does seem safe.
> [New] add default support for `paths` to include `$HOME/.node_{modules,libraries}`

- appveyor.yml
- lib/async.js
- lib/sync.js
Fixes #283.
Test results:
- before fix https://ci.appveyor.com/project/pos777/resolve/builds/43631834
- after fix https://ci.appveyor.com/project/pos777/resolve/builds/43632685
> Fix: resolve result is inconsistent with require.resolve if windows virtual drive is used

- .editorconfig
According to [editorconfig docs](https://editorconfig.org/#supported-properties) `off` is not a valid value, but `unset` should be used.
Fixes #272
> Fix invalid values in editorconfig

- package.json
Use double quotes in cmd argument.
Resolve deprecation warning for `--production`.
Closes: https://github.com/browserify/resolve/issues/331
> [Tests] fix posttest script on Windows
